### ISSUE TITLE
Trained Model

### ISSUE THREAD

**Issue by Gujojo** [jinningli/IP-FSRGAN#1]
Hello, 
is there any trained models available for reproducing your work?

**Comment by jinningli** [comment]
Hi,
I am afraid I have no pre-trained model. This work finished when I was intern in one company. The pre-trained model was saved on their server and I was not permitted to download or share it. 

Thanks

**Comment by jinningli** [comment]
Alternatively, you should be able to train your own with other public dataset.

**Comment by Gujojo** [comment]
Thanks, I will have a try.
